# Generated by Django 2.2.4 on 2019-08-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/%Y/%m/%d'),
        ),
    ]
